### ISSUE TITLE
Up/down arrow triggers window scrolling

### ISSUE THREAD

**Issue by danielthedifficult** [windusayles/slotty-machine#1]
This is probably only an issue if you're going to use a keyboard for the actual game, but it's definitely annoying 🙄 

Solutions:
1. CSS: `overflow: hidden` to clip the window
```CSS
html, body {
    overflow: 'hidden',
    height: '100%'
}
```
2. JS : add `key.preventDefault()` on keydown triggers here:
https://github.com/windusayles/slotty-machine/blob/b32a0eef98c4f41606d57812ab3a5692380ad2ab/src/core/Scoreboard.ts#L79-L85

3. Use different keys like +/- 😆
